ARG PYTHON_VERSION=3.10

FROM python:${PYTHON_VERSION}-bullseye

WORKDIR /root

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app.py wsgi.py ./

COPY templates ./templates

CMD [ "sh", "-c", "uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app"]

