FROM python:3-bullseye

WORKDIR root

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app.py wsgi.py .

COPY templates ./templates

CMD uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app

